---
# - name: install required packages
#   apt:
#     name: '{{ item }}'
#     state: present
#   with_items:
#     - python
#     - python-serial

- name: Stop services
  systemd:
    name: '{{ item }}'
    state: stopped
  with_items:
   - gpsd
   - chrony

#install tool for ublox config
- name: Copy program for config
  synchronize:
    src: files/ubx-packet-exchange/
    dest: /opt/ubx-packet-exchange/
    rsync_opts:
      - "--no-motd"
      - "--exclude=.git"
      - "--exclude=.vscode"
  tags: config


- name: disable sbas; enable gps and galileo
  command: python /opt/ubx-packet-exchange/ubloxmsg_exchange.py /opt/ubx-packet-exchange/config_files/config_time /dev/ttyO2


- name: Enable services
  systemd:
    name: '{{ item.name }}'
    state: restarted
    enabled: '{{ item.enabled }}'
    daemon_reload: yes
  with_items:
   - { name: chrony, enabled: no }
   - { name: chrony.path, enabled: yes }
   - { name: gpsd, enabled: yes}
  tags: conf
