---
- name: Prepare paths for service override
  file:
    path: '/etc/systemd/system/{{ item }}.service.d'
    state: directory
    recurse: yes
  with_items:
   - gpsd
   - chrony
  tags: conf

- name: Override service configs
  copy:
    src: '{{ item }}.override.conf'
    dest: '/etc/systemd/system/{{ item }}.service.d/override.conf'
  with_items:
    - chrony
    - gpsd
  tags: conf

- name: Add config systemd service
  template:
    src: 'ublox-config.service'
    dest: '/etc/systemd/system/'
  tags: conf

# services not started at boot, but after respective file exists
- name: Add service path activation
  copy:
    src: 'chrony.path'
    dest: '/etc/systemd/system/chrony.path'
  tags: conf

- name: Enable services
  systemd:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    enabled: '{{ item.enabled }}'
    daemon_reload: yes
  with_items:
   - { name: gpsd.service, enabled: yes, state: restarted }
   - { name: chrony.service, enabled: no, state: restarted }
   - { name: chrony.path, enabled: yes, state: restarted }
   - { name: ublox-config.service, enabled: yes, state: stopped }
  tags: conf