language: c

services:
  - docker

script:
 - export PROJECT_DIR=$PWD
 - cd software/packaging
 - docker build -t shepherd-builder-img .
 - docker create -it --name shepherd-builder shepherd-builder-img
 - docker cp $PROJECT_DIR/software shepherd-builder:/code
 - docker start -a shepherd-builder
 - docker cp shepherd-builder:/artifacts $PROJECT_DIR/
 - cd $PROJECT_DIR

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: "artifacts/latest/*"
  skip_cleanup: true
