--- # This will switch to alternative repo for newer python versions
- name: Install dependency to extend apt-repos
  ansible.builtin.apt:
    name: software-properties-common
    state: present
    update_cache: true
  when: false

- name: Add nginx stable repository from PPA and install its signing key on Debian target
  ansible.builtin.apt_repository:
    repo: 'ppa:deadsnakes/ppa'
    codename: deadsnakes

- name: Install dependency to extend apt-repos
  ansible.builtin.apt:
    name: ["python3.10-dev", "python3.10-venv", "python3.10-distutils"]
    state: present
    update_cache: true

# TODO: not finished - make usable with just calling python, also install packages
