---
- name: Install ptp package
  ansible.builtin.apt:
    update_cache: true
    name: linuxptp
    state: present
  tags: ptp

- name: Create systemd overlay directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: 'a+rwx'
  loop:
    - /etc/systemd/system/phc2sys.service.d/
    - /etc/systemd/system/ptp4l.service.d/
  tags:
    - ptp
    - conf

- name: Deploy systemd overlay files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/etc/systemd/system/{{ item.dest }}"
    mode: '0644'
  loop:
    - {
      src: "phc2sys_mands.conf",
      dest: "phc2sys.service.d/phc2sys_mands.conf",
    }
    - {
      src: "ptp_restart.conf",
      dest: "ptp4l.service.d/ptp_restart.conf"
    }
  tags:
    - ptp
    - conf

- name: Disable services (some entries will fail)
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    daemon_reload: true
  loop:
    - phc2sys.service # TODO: these fail in recent ubuntu nightlies, linuxptp switched to servive-templates, keep old style for now
    - ptp4l.service
    - phc2sys@eth0.service
    - ptp4l@eth0.service
  failed_when: false  # services may not exist
  tags:
    - ptp
    - conf
