---
- name: Make sure TI software path exists
  ansible.builtin.file:
    path: '{{ ti_path }}'
    state: directory
    mode: '0644'
  become: true
  tags:
    - pru-tools

- name: Download and extract pru software support package
  ansible.builtin.unarchive:
    src: 'http://git.ti.com/cgit/cgit.cgi/pru-software-support-package/pru-software-support-package.git/snapshot/{{ pru_support_package }}.tar.gz'
    dest: '{{ ti_path }}'
    remote_src: true
  become: true
  tags:
    - pru-tools

- name: Download PRU Code Generation tools installer
  ansible.builtin.get_url:
    url: '{{ pru_cgt_installer }}'
    dest: /tmp/
    timeout: 120
    mode: a+x
  register: get_url_ret
  become: true
  tags:
    - pru-tools

- name: Install PRU Code Generation tools
  ansible.builtin.command: '{{ get_url_ret.dest }}'
  become: true
  changed_when: true
  tags:
    - pru-tools

- name: Prepare path to link binaries
  ansible.builtin.file:
    path: '{{ pru_cgt_path }}/bin'
    state: directory
    recurse: true
  become: true
  tags:
    - pru-tools

- name: Symlink PRU compiler and linker
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - { src: /usr/bin/clpru, dest: '{{ pru_cgt_path }}/bin/clpru' }
    - { src: /usr/bin/lnkpru, dest: '{{ pru_cgt_path }}/bin/lnkpru' }
  become: true
  tags:
    - pru-tools

- name: Adding PRU environment vars in bashrc file
  ansible.builtin.lineinfile:
    dest: '{{ item[1] }}/.bashrc'
    line: 'export {{ item[0]["name"] }}={{ item[0]["path"] }}'
    insertafter: 'EOF'
    state: present
  with_nested:
    - [
      { name: PRU_CGT, path: '{{ pru_cgt_path }}' },
      { name: PRU_SUPPORT, path: '{{ ti_path }}/{{ pru_support_package }}' }
    ]
    - ['/home/{{ ansible_user }}', '/root']
  become: true
  tags:
    - pru-tools
