---
- name: Role - Sheep
  hosts: sheep

  roles:
    - dev-host
    - sheep
    - gps-host
    - ptp-host

  handlers:
    - name: Restart device
      ansible.builtin.reboot:

  pre_tasks:
    - name: Get time and date from ansible controller
      ansible.builtin.command: 'date -u +"%Y-%m-%dT%H:%M:%SZ"'
      delegate_to: localhost
      changed_when: false
      register: local_time
      become: false
    - name: Set correct time
      ansible.builtin.command: "date -s {{ local_time.stdout }}"
      changed_when: true
  become: true

- name: Role - PTP-Client
  hosts: ptp_clients
  roles:
    - ptp-client
  become: true

- name: Role - NTP-Client
  hosts: ntp_clients
  roles:
    - ntp-client
  become: true

- name: Role - GPS-Client
  hosts: gps_clients
  roles:
    - gps-client  # TODO: how to avoid allowing gps & ptp & ntp client? trouble ahead
  become: true

- name: Role - PTP-Server
  hosts: ptp_servers
  roles:
    - ptp-server
  become: true

- name: Role - Secured Testbed
  hosts: secured
  roles:
    - secure-testbed
  become: true
