---
- name: delete space wasting or forgotten files (WARNING - includes recordings) and cleans up free space to prepare image-extraction
  hosts: all
  become: true

  vars_prompt:
    - name: confirmation
      prompt: "Do you really want to continue?"
      private: no
      default: "yes"

  tasks:

  - name: delete Logs and other tmp-files
    command: "rm -rf {{item}}"
    with_items:
      - /var/log/*
      - /var/lib/apt/lists
    when: confirmation | bool
    # note: ansible.builtin.file would have been preferred, but it has a problem with wildcards

  - name: delete recordings
    command: "rm -rf {{item}}"
    with_items:
      - /var/shepherd/recordings/*
      - /var/shepherd/recordings2/*
    when: confirmation | bool

  - name: Optimize Boot by removing outdated initrd
    command: "rm -rf /boot/initrd.img*"
    when: confirmation | bool

  - name: clean apt-cache
    command: apt clean
    when: confirmation | bool

  - name: Discard unused blocks (trim)
    command: fstrim -a
