---
- name: Delete space wasting or forgotten files (WARNING - includes recordings) and cleans up free space to prepare image-extraction
  hosts: all
  become: true

  vars_prompt:
    # these can be also passed as argument:  -e "zero_empty_space=True" -> automatically skips these prompts
    - name: zero_empty_space
      prompt: "Do you want to zero-out empty space at the end (prereq for image-creation)?"
      private: false
      default: "no"

  tasks:

    - name: Confirm delete-process
      ansible.builtin.pause:
        prompt: "Do you really want to continue to delete recordings and more?"

    - name: Find Logs and other tmp-files
      ansible.builtin.find:
        paths: ["/var/log/", "/var/lib/apt/lists"]
        patterns: '*'
        recurse: true
      register: files_tmp
    - name: Delete Logs and other tmp-files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_tmp.files }}"

    - name: Find recordings
      ansible.builtin.find:
        paths: ["/var/shepherd/recordings/", "/var/shepherd/recordings2/"]
        patterns: '*'
        recurse: true
      register: files_rec
    - name: Delete recordings
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_rec.files }}"

    - name: Optimize Boot by removing outdated initrd - find files with Wildcard
      # ansible.builtin.command: "rm -rf /boot/initrd.img*"
      ansible.builtin.find:
        paths: '/boot'
        patterns: 'initrd.img*'
      register: files_init
    - name: Optimize Boot by removing outdated initrd - delete files found previously
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_init.files }}"

    - name: Clean apt-caches - A
      ansible.builtin.apt:
        autoremove: true
    - name: Clean apt-caches - B
      ansible.builtin.apt:
        autoclean: true
    - name: Clean apt-caches - C
      ansible.builtin.apt:
        clean: true

    - name: Discard unused blocks (trim)
      ansible.builtin.command: 'fstrim -a'
      changed_when: true

    - name: Restart device
      ansible.builtin.reboot:
      when: zero_empty_space

    - name: Overwrite empty space
      ansible.builtin.command: 'dd if=/dev/zero of=/opt/zero_file bs=4M'
      failed_when: false  # will write zeros until it fails
      changed_when: true
      when: zero_empty_space

    - name: Sync
      ansible.builtin.command: 'sync'
      changed_when: true
      when: zero_empty_space

    - name: remove empty space
      ansible.builtin.file:
        path: '/opt/zero_file'
        state: absent

    - name: Discard unused blocks (trim)
      ansible.builtin.command: 'fstrim -a'
      changed_when: true
