---
- name: delete space wasting or forgotten files (WARNING - includes recordings) and cleans up free space to prepare image-extraction
  hosts: all
  become: true

  vars_prompt:
    - name: confirmation
      prompt: "Do you really want to continue?"
      private: false
      default: "yes"

  tasks:

  - name: delete Logs and other tmp-files
    ansible.builtin.command: "rm -rf {{item}}"
    with_items:
      - /var/log/*
      - /var/lib/apt/lists
    when: confirmation | bool
    changed_when: true
    # note: ansible.builtin.file would have been preferred, but it has a problem with wildcards

  - name: delete recordings
    ansible.builtin.command: "rm -rf {{item}}"
    with_items:
      - /var/shepherd/recordings/*
      - /var/shepherd/recordings2/*
    when: confirmation | bool
    changed_when: true

  - name: Optimize Boot by removing outdated initrd
    ansible.builtin.command: "rm -rf /boot/initrd.img*"
    when: confirmation | bool
    changed_when: true

  - name: Clean apt-caches - A
    ansible.builtin.apt:
      autoremove: true
  - name: Clean apt-caches - B
    ansible.builtin.apt:
      autoclean: true
  - name: Clean apt-caches - C
    ansible.builtin.apt:
      clean: true

  - name: Discard unused blocks (trim)
    ansible.builtin.command: 'fstrim -a'
    changed_when: true
