---
- name: Refresh Src, compile and install PRU-Fw, restart Kernel-Module, reinstall py-package, without Reboot
  hosts: all
  become: true

  vars_prompt:
    # these can be also passed as argument:  -e "refresh_from_git=True" -> automatically skips these prompts
    - name: refresh_from_host
      prompt: "Do you want to distribute the shepherd-source from host to nodes?"
      private: false
      default: "no"

  tasks:

    - name: Rebuild Software
      ansible.builtin.include_role:
        name: sheep
      vars:
        install_basics: false
        shepherd_branch: dev  # default: main
        refresh_source: "{{ refresh_from_host }}"
        rebuild_kernel_module: true  # default: true
        rebuild_python_package: true # default: true
