---
- name: Apply performance enhancing Changes (use less ram, boot faster)
  hosts: all
  become: true

  tasks:

  - name: CFG - Improve SSH-Speed
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "{{ item.regex }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - {regex: '^.*UseDNS.*$', line: 'UseDNS no'}
      - {regex: '^.*Compression.*$', line: 'Compression no'}

  - name: CFG - Adapt default Target to multi-user
    command: systemctl set-default multi-user
    # check with: sudo systemctl get-default

  - name: CFG - Disable Graphical.target
    #command: systemctl disable graphical.target
    systemd:
      name: graphical.target
      enabled: no
      state: stopped
      daemon_reload: yes

  - name: CFG - Optimize Boot by removing outdated initrd
    command: "rm -rf /boot/initrd.img*"
    # note: ansible.builtin.file would have been preferred, but it has a problem with wildcards
