---
- name: Apply performance enhancing Changes (use less ram, boot faster)
  hosts: all
  become: true

  tasks:

  - name: CFG - Improve SSH-Speed
    ansible.builtin.lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "{{ item.regex }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - {regex: '^.*UseDNS.*$', line: 'UseDNS no'}
      - {regex: '^.*Compression.*$', line: 'Compression no'}

  - name: CFG - Adapt default Target to multi-user
    ansible.builtin.command: 'systemctl set-default multi-user'
    changed_when: true
    # check with: sudo systemctl get-default

  - name: CFG - Disable Graphical.target
    ansible.builtin.systemd:
      name: graphical.target
      enabled: false
      state: stopped
      daemon_reload: true

  - name: Optimize Boot by removing outdated initrd - find files with Wildcard
    # ansible.builtin.command: "rm -rf /boot/initrd.img*"
    ansible.builtin.find:
      paths: '/boot'
      patterns: 'initrd.img*'
    register: files_init
  - name: Optimize Boot by removing outdated initrd - delete files found previously
    ansible.builtin.find:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_init.files }}"
