---
# proposed by helpdesk - login-server and dgw share home-directory
# hard to do as a role because of vars_prompt of temp user-data
# TODO: maybe it is better to store a set of authorized keys and distribute them

- name: Add (network) datastorage to remote nodes
  hosts: all
  become: true
  gather_facts: true

  vars:
    key_server: login.zih.tu-dresden.de
    data_server: dgw.zih.tu-dresden.de
    data_path_remote: /svm/vs-grp04/shepherdDS
    # data will be stored in {{data_path_remote}}/recordings/{{ansible_hostname}}/
    data_path_local: /var/shepherd/recordings/

  vars_prompt:
    - name: zih_user
      prompt: "Please provide ZIH username with access to storage (will not be stored)"
      private: false
    - name: zih_password
      prompt: "users password"
      private: true

  pre_tasks:

    - name: Fail if prerequisites are missing
      ansible.builtin.fail:
        msg: "The variable '{{item}}' is not defined"
      when: (item is not defined) or (item|length < 1)
      loop:
        - key_server
        - data_server
        - data_path_remote
        - data_path_local
        - zih_user
        - zih_password

    - name: Report hostname
      ansible.builtin.debug:
        var: ansible_hostname

    - name: Check if key-pair is present on remote node
      ansible.builtin.stat:
        path: "~/.ssh/id_rsa.pub"
      register: key_file
      become: false

    - name: Generate fresh key-pair (if needed)
      ansible.builtin.shell:
        cmd: 'ssh-keygen -q -t rsa -N "" -C cfaed_nes_shepherd_node'
      when: not key_file.stat.exists
      become: false

  tasks:

    - name: APT - Install required packages
      ansible.builtin.apt:
        name: ["sshfs", "sshpass"]
        state: present
        update_cache: true

    - name: Authorize remote node with key-server
      ansible.builtin.shell:
        cmd: "sshpass -e ssh-copy-id -f -i ~/.ssh/id_rsa.pub {{zih_user}}@{{key_server}}"
      environment:
        SSHPASS: '{{zih_password}}'
      become: false

    # NOTE: this is an extreme workaround:
    #   - login-server can ssh but has datastorage not mounted
    #   - data-server can't ssh, and scp a directory-structure fails because of permissions
    - name: Create temporary mnt-structure
      ansible.builtin.file:
        path: "/tmp/smnt/"
        state: directory
        mode: "a+rwx"
      become: false

    - name: Create remote private recordings-directory
      ansible.builtin.command:
        cmd: "sshfs {{zih_user}}@{{data_server}}:{{data_path_remote}} /tmp/smnt/"
      become: false

    - name: Create remote directory-structure
      ansible.builtin.file:
        path: "/tmp/smnt/recordings/{{ansible_hostname}}/"
        state: directory
        mode: "a+rwx"
      become: false

#    - name: Create remote private recordings-directory
#      ansible.builtin.command:
#        cmd: "scp -r /tmp/recordings {{zih_user}}@{{data_server}}:{{data_path_remote}}/'"
#      become: false

    - name: Create local mount-directory
      ansible.builtin.file:
        path: "{{data_path_local}}/"
        state: directory
        owner: "{{ansible_user}}"
        mode: 'a+rwx'

    - name: Enable automatic mounting
      ansible.builtin.lineinfile:
        dest: '/home/{{ ansible_user }}/.bashrc'
        regex: '^.*sshfs.*$'
        line: "sshfs {{zih_user}}@{{data_server}}:{{data_path_remote}}/recordings/{{ansible_hostname}}/ {{data_path_local}}"
        state: present

  post_tasks:

    - name: Restart device
      ansible.builtin.reboot:
        connect_timeout: 20
        reboot_timeout: 200
