---

- name: Look for Kernel Module
  ansible.builtin.command: 'modinfo shepherd'
  register: modinfo_ret
  failed_when: false
  changed_when: false

- name: Stop Kernel Module
  ansible.builtin.command: 'modprobe -rf shepherd'
  register: modprobe_ret
  until: modprobe_ret is not failed
  retries: 5
  when: not modinfo_ret
  changed_when: true
  # fails at least on first install -> check for presence of shepherd
  # lsmod | grep shepherd  -> $? is still 0 if present
  # modinfo could work -> test above

- name: Check if PRU1 is present
  ansible.builtin.stat:
    path: "/sys/class/remoteproc/remoteproc1/state"
  register: sysfs_pru
- name: Stop PRU1
  ansible.builtin.shell:
    cmd: 'echo "stop" > /sys/class/remoteproc/remoteproc1/state'
  when: sysfs_pru.stat.exists
  failed_when: false
  changed_when: true

- name: Check if PRU2 is present
  ansible.builtin.stat:
    path: "/sys/class/remoteproc/remoteproc2/state"
  register: sysfs_pru
- name: Stop PRU2
  ansible.builtin.shell:
    cmd: 'echo "stop" > /sys/class/remoteproc/remoteproc2/state'
  when: sysfs_pru.stat.exists
  failed_when: false
  changed_when: true

- name: Uninstall shepherd python package
  ansible.builtin.pip:
    name: "./"
    state: absent
    chdir: '{{ shepherd_install_path }}/software/python-package'
  failed_when: false
  tags:
    - install
    - python
  when: rebuild_python_package | bool
  # TODO: maybe not needed

- name: Own shepherd codebase
  ansible.builtin.file:
    path: "{{ shepherd_install_path }}/"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "a+rw"
    recurse: true
  become: true
  tags:
    - source-code
    - python

- name: GIT - Update Shepherd-Codebase
  ansible.builtin.git:
    repo: https://github.com/orgua/shepherd
    dest: "{{ shepherd_install_path }}"
    update: true
    version: "{{ shepherd_branch }}"
    force: true
  when: refresh_source | bool
  become: false
