---

- name: Configure Shepherd - Pre-Phase
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  items:
    - config_folders.yml
    - config_overlays.yml
  when: install_basics | bool
  tags:
    - install

- name: Install Pre-Requisits
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  items:
    - toolchain_kernel.yml
    - toolchain_py.yml
  when: install_basics | bool
  tags:
    - install

- name: Install Ti-Toolchain for PRU
  ansible.builtin.include_tasks:
    file: toolchain_pru_ti.yml
  when:
    - install_basics | bool
    - install_ti_tools | bool
  tags:
    - install

- name: Install GCC-Toolchain for PRU
  ansible.builtin.include_tasks:
    file: toolchain_pru_gcc.yml
  when:
    - install_basics | bool
    - install_gcc_tools | bool
  tags:
    - install

- name: Restart device after installing PreReqs
  ansible.builtin.reboot:
  when: install_basics | bool

- name: Build Shepherd-Software
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  items:
    - build_pre.yml
    - build_shp.yml
    - build_post.yml
  tags:
    - install
    - build

- name: Configure Shepherd - Post-Phase
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  items:
    - config_shepherd.yml
    - config_systemd.yml
  when: install_basics | bool
  tags:
    - install

- name: Restart device after setup
  ansible.builtin.reboot:
  when: install_basics | bool
