---

### Install & Config
- name: Configure Shepherd - Pre-Phase
  ansible.builtin.include_tasks:
    file: "{{ file_item }}"
  loop:
    - config_folders.yml
    - config_overlays.yml
  loop_control:
    loop_var: file_item
  when: install_basics | bool
  tags:
    - install

- name: Install Pre-Requisits
  ansible.builtin.include_tasks:
    file: "{{ file_item }}"
  loop:
    - toolchain_kernel.yml
    - toolchain_py.yml
  loop_control:
    loop_var: file_item
  when: install_basics | bool
  tags:
    - install

- name: Install Ti-Toolchain for PRU
  ansible.builtin.include_tasks:
    file: toolchain_pru_ti.yml
  when:
    - install_basics | bool
    - install_ti_tools | bool
  tags:
    - install

- name: Install GCC-Toolchain for PRU
  ansible.builtin.include_tasks:
    file: toolchain_pru_gcc.yml
  when:
    - install_basics | bool
    - install_gcc_tools | bool
  tags:
    - install

- name: Restart device after installing PreReqs (& changing overlays)
  ansible.builtin.reboot:
    connect_timeout: 20
    reboot_timeout: 200
  when: install_basics | bool

### Build
- name: Build Shepherd-Software
  ansible.builtin.include_tasks:
    file: "{{ file_item }}"
  loop:
    - build_pre.yml
    - build_shp.yml
    - build_post.yml
  loop_control:
    loop_var: file_item
  tags:
    - install
    - build

### Config
- name: Configure Shepherd - Post-Phase
  ansible.builtin.include_tasks:
    file: "{{ file_item }}"
  loop:
    - config_shepherd.yml
    - config_systemd.yml
  loop_control:
    loop_var: file_item
  when: install_basics | bool
  tags:
    - install

- name: Restart device after setup (specially services)
  ansible.builtin.reboot:
    connect_timeout: 20
    reboot_timeout: 200
  when: install_basics | bool
