---

- name: Get kernel version
  ansible.builtin.command: 'uname --kernel-release'
  register: kernelrelease
  changed_when: false

- name: APT - Install required packages for kernel compilation
  ansible.builtin.apt:
    name:
      [
        "linux-headers-{{ kernelrelease.stdout.strip() }}", # TODO: done by bootstrap / maintenance
        "linux-firmware", # TODO: is already there
        "dkms",
      ]
    state: present
    update_cache: true
