name: Test Repo

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04 # TODO: -latest was 20.04 and had old packages
    strategy:
      matrix:
        python-version: ["3.10", "3.8"]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} 🐍
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies 🔧
        run: |
          sudo apt install python3-msgpack
          sudo apt install cppcheck
          python3 -m pip install --upgrade pip msgpack
          pip3 install pylint pylint-exit pylint-pytest
        # NOTE: install-process fails without msgpack pre-installed
        # NOTE: cppcheck is needed for pre-commit

      - name: Run Pre-Commit Tests 🧪
        uses: pre-commit/action@v3.0.0

      - name: Install the shepherd py-package 🐑
        run: "sudo pip3 install ./[test]"
        working-directory: "./software/python-package"
      - name: Test the shepherd py-package (limited test-range) 🐐
        run: "sudo pytest"
        working-directory: "./software/python-package"
        # needs sudo because it installs packages
      - name: PyLint the shepherd py-package 🐏
        run: "pylint $(git ls-files '*.py') || pylint-exit $?"
        # -E --py-version 3.8
        working-directory: "software/python-package/"

      - name: Install the shepherd-herd py-package 𓋿 𓀍
        run: "sudo pip3 install ./"
        working-directory: "./software/shepherd-herd"
